name: ci-cd-web-tech

services:
  jenkins:
    image: jenkins/jenkins:2.551
    networks:
      cafe-net:
        aliases:
          - cafe-app
    ports:
      - "8083:8080"
      - "8081:8081"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    networks:
      - cafe-net
    ports:
      - "4444:4444"
      - "7900:7900"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "--url=daily-lenient-kiwi.ngrok-free.app"
      - "cafe-app:8081"
    environment:
      NGROK_AUTHTOKEN: "YOUR_TOKEN"
    networks:
      - cafe-net
    depends_on:
      - jenkins

networks:
  cafe-net:
    driver: bridge

volumes:
  jenkins_data: