spring:
  application:
    name: mase-cafe-project
  datasource:
    url: jdbc:mysql://localhost:3306/cafe_system_db
    username: root
    password: RootRoot##
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8081
  error:
    include-stacktrace: always
    include-exception: true

jwt:
  secret: QN4HTijhnwrmBIFiE/x76umO3AgPZ5w3M1c4ophax5E=
  get:
    token:
      uri: /authenticate